#Chapter 1 session
#Mon Jul 13 16:22:44 MSK 2026
trust=0
hackAttempts=0
suspicion=4
terminal=false
battleCardGranted=false
cipherSolved=false
inspected=CHEST,LEGS,BOOTS
loop=8
fragments=1001
escapeUnlocked=false
prison=16
battleCardIcon=false
